#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@71d20029c5314dfc34f3bbdab808b9bce03b8003
    with:
      duckdb_version: v1.3.0
      ci_tools_version: 71d20029c5314dfc34f3bbdab808b9bce03b8003
      extension_name: vortex
      exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;windows_amd64_mingw;windows_amd64;linux_arm64"
      extra_toolchains: "rust"
      override_ci_tools_repository: spiraldb/extension-ci-tools
